name: biobb_ligand_parameterization_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.7
  - biobb_common==3.0.0
  - biobb_io==3.0.0
  - biobb_chemistry==3.0.1
  - nb_conda_kernels
  - nglview
  - conda