name: biobb_ligand_parameterization_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_io==4.1.0
  - biobb_chemistry==4.1.0
  - jupyter_client==7.3.2
  - nb_conda_kernels
  - traitlets==5.9.0
  - jupyter_contrib_nbextensions
  - nglview
  - conda