name: biobb_ligand_parameterization_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_io==4.0.0
  - biobb_chemistry==4.0.0
  - ipywidgets==7.6.6
  - jupyter_client==7.3.2
  - tornado==6.1
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - nglview
  - conda