name: biobb_ligand_parameterization_tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_io==4.1.0
  - biobb_chemistry==4.1.0
  - nb_conda_kernels
  - importlib_metadata
  - jupyter_contrib_nbextensions
  - nglview
  - conda